services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            - WWWUSER=${WWWUSER:-1000}
            - WWWGROUP=${WWWGROUP:-1000}
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
    phpmyadmin:
            image: phpmyadmin/phpmyadmin
            ports:
                - '8081:80'
            environment:
                PMA_HOST: mysql
                PMA_ARBITRARY: 1
            depends_on:
                - mysql
volumes:
    sail-mysql:
        driver: local
